#
# +------------------------------------------------------+ #
# |     Config - nic tu nie ma... na razie...            | #
# +------------------------------------------------------+ #
#
# 
# 
# 
# 
# 
